### ISSUE TITLE
define __init__() to simplify usage

### ISSUE THREAD

**Issue by bjarthur** [aviks/Taro.jl#32]
the docs say one has to `Taro.init()` before doing anything.  you should consider doing this automatically for the user in an `__init__()` function as described [here](https://docs.julialang.org/en/latest/manual/modules.html#Module-initialization-and-precompilation-1).  as an example see [FreeTypeAbstraction.jl](https://github.com/JuliaGraphics/FreeTypeAbstraction.jl/blob/master/src/FreeTypeAbstraction.jl#L15).

**Comment by aviks** [comment]
There is a complication with the use of the JVM that drives this design. 

There can only be one embedded JVM per process. And the classpath used by the JVM can only be set before it is initialised. Therefore, if a user wants to use, within Julia, two packages that load the JVM (say Taro and JDBC), I need to give them the ability to manually configure the classpath for both the projects. Otherwise, the first package for which you do an `using` will load, and the second cannot be used. 

So this is the reason why I don't do automatic loading of the JVM when loading the Julia module.

**Comment by bjarthur** [comment]
i see.  you might want to briefly mention this in Usage section of the docs, as it is something that that an inexperienced Java user, like me, would stumble on.
